// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyBasicWebApiDemo.Data;

#nullable disable

namespace MyBasicWebApiDemo.Migrations
{
    [DbContext(typeof(SampleDbContext))]
    partial class SampleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-rc.1.23419.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyBasicWebApiDemo.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e9c6ad6c-8529-404c-81de-277394129b44"),
                            Name = ".NET"
                        },
                        new
                        {
                            Id = new Guid("5b3c2e4c-97ba-4cb8-8b23-d6b7039cb027"),
                            Name = "Cloud"
                        },
                        new
                        {
                            Id = new Guid("ffdd0d80-3c3b-4e83-84c9-025d5650c6e5"),
                            Name = "DevOps"
                        });
                });

            modelBuilder.Entity("MyBasicWebApiDemo.Models.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CategoryId");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Content");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Posts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b36194c2-35ca-4e47-b57e-edcb080501a9"),
                            CategoryId = new Guid("e9c6ad6c-8529-404c-81de-277394129b44"),
                            Content = "Post 1 content",
                            Title = "Post 1"
                        },
                        new
                        {
                            Id = new Guid("fd32ed91-c9d4-4cf6-9ad5-9d5182b0b0a8"),
                            CategoryId = new Guid("e9c6ad6c-8529-404c-81de-277394129b44"),
                            Content = "Post 2 content",
                            Title = "Post 2"
                        },
                        new
                        {
                            Id = new Guid("26800853-5c1a-4132-aa29-98cf7a9e0cf7"),
                            CategoryId = new Guid("e9c6ad6c-8529-404c-81de-277394129b44"),
                            Content = "Post 3 content",
                            Title = "Post 3"
                        },
                        new
                        {
                            Id = new Guid("5604b6fc-69de-443c-9a36-c09787732492"),
                            CategoryId = new Guid("e9c6ad6c-8529-404c-81de-277394129b44"),
                            Content = "Post 4 content",
                            Title = "Post 4"
                        },
                        new
                        {
                            Id = new Guid("a5a15fcd-46f9-4c38-9711-3ea72fd14544"),
                            CategoryId = new Guid("e9c6ad6c-8529-404c-81de-277394129b44"),
                            Content = "Post 5 content",
                            Title = "Post 5"
                        },
                        new
                        {
                            Id = new Guid("7eea01a9-123d-4201-8137-881045d9e0d4"),
                            CategoryId = new Guid("e9c6ad6c-8529-404c-81de-277394129b44"),
                            Content = "Post 6 content",
                            Title = "Post 6"
                        },
                        new
                        {
                            Id = new Guid("fb34dada-3d45-496b-a1dd-7ed7d7599f78"),
                            CategoryId = new Guid("e9c6ad6c-8529-404c-81de-277394129b44"),
                            Content = "Post 7 content",
                            Title = "Post 7"
                        },
                        new
                        {
                            Id = new Guid("71e7fe2f-1354-427c-a385-432c60e420fe"),
                            CategoryId = new Guid("e9c6ad6c-8529-404c-81de-277394129b44"),
                            Content = "Post 8 content",
                            Title = "Post 8"
                        },
                        new
                        {
                            Id = new Guid("d328e162-f7c3-41e5-b529-7ca197f5c9b2"),
                            CategoryId = new Guid("e9c6ad6c-8529-404c-81de-277394129b44"),
                            Content = "Post 9 content",
                            Title = "Post 9"
                        },
                        new
                        {
                            Id = new Guid("f9338a91-d56f-41d5-99c7-cf579f773615"),
                            CategoryId = new Guid("e9c6ad6c-8529-404c-81de-277394129b44"),
                            Content = "Post 10 content",
                            Title = "Post 10"
                        },
                        new
                        {
                            Id = new Guid("6bf0dd43-cf69-49b2-aa62-3605015b979b"),
                            CategoryId = new Guid("5b3c2e4c-97ba-4cb8-8b23-d6b7039cb027"),
                            Content = "Post 11 content",
                            Title = "Post 11"
                        },
                        new
                        {
                            Id = new Guid("9d902c31-e949-4a48-a12d-2e4bcfcefca6"),
                            CategoryId = new Guid("5b3c2e4c-97ba-4cb8-8b23-d6b7039cb027"),
                            Content = "Post 12 content",
                            Title = "Post 12"
                        },
                        new
                        {
                            Id = new Guid("dbfa827a-918d-4dc9-a13b-592d39896f7e"),
                            CategoryId = new Guid("5b3c2e4c-97ba-4cb8-8b23-d6b7039cb027"),
                            Content = "Post 13 content",
                            Title = "Post 13"
                        },
                        new
                        {
                            Id = new Guid("c3d60a94-9229-4991-a91e-942be7dc3a03"),
                            CategoryId = new Guid("5b3c2e4c-97ba-4cb8-8b23-d6b7039cb027"),
                            Content = "Post 14 content",
                            Title = "Post 14"
                        },
                        new
                        {
                            Id = new Guid("63833b12-a9f4-4a85-a885-de41d0761692"),
                            CategoryId = new Guid("5b3c2e4c-97ba-4cb8-8b23-d6b7039cb027"),
                            Content = "Post 15 content",
                            Title = "Post 15"
                        },
                        new
                        {
                            Id = new Guid("5cabcaf6-1826-4bdb-a49c-dbeebba483e9"),
                            CategoryId = new Guid("5b3c2e4c-97ba-4cb8-8b23-d6b7039cb027"),
                            Content = "Post 16 content",
                            Title = "Post 16"
                        },
                        new
                        {
                            Id = new Guid("52280c5b-f9a2-4916-8189-9ce641e1c3e5"),
                            CategoryId = new Guid("5b3c2e4c-97ba-4cb8-8b23-d6b7039cb027"),
                            Content = "Post 17 content",
                            Title = "Post 17"
                        },
                        new
                        {
                            Id = new Guid("ba15df11-1afd-4643-a26c-3517e62a865e"),
                            CategoryId = new Guid("5b3c2e4c-97ba-4cb8-8b23-d6b7039cb027"),
                            Content = "Post 18 content",
                            Title = "Post 18"
                        },
                        new
                        {
                            Id = new Guid("aa106b05-248a-437c-b2ee-5e1fcb1e3375"),
                            CategoryId = new Guid("5b3c2e4c-97ba-4cb8-8b23-d6b7039cb027"),
                            Content = "Post 19 content",
                            Title = "Post 19"
                        },
                        new
                        {
                            Id = new Guid("7e9c3110-07ca-43aa-b608-e8db044eaf62"),
                            CategoryId = new Guid("5b3c2e4c-97ba-4cb8-8b23-d6b7039cb027"),
                            Content = "Post 20 content",
                            Title = "Post 20"
                        },
                        new
                        {
                            Id = new Guid("355b1887-67fe-406e-990c-e6c8ca38a17c"),
                            CategoryId = new Guid("ffdd0d80-3c3b-4e83-84c9-025d5650c6e5"),
                            Content = "Post 21 content",
                            Title = "Post 21"
                        },
                        new
                        {
                            Id = new Guid("2b19201b-fc29-4414-b894-135145269966"),
                            CategoryId = new Guid("ffdd0d80-3c3b-4e83-84c9-025d5650c6e5"),
                            Content = "Post 22 content",
                            Title = "Post 22"
                        },
                        new
                        {
                            Id = new Guid("322a795b-c6cc-4199-9945-7d3ab9ad7806"),
                            CategoryId = new Guid("ffdd0d80-3c3b-4e83-84c9-025d5650c6e5"),
                            Content = "Post 23 content",
                            Title = "Post 23"
                        },
                        new
                        {
                            Id = new Guid("b7a60a7c-7627-490f-a04d-8f7f803cc490"),
                            CategoryId = new Guid("ffdd0d80-3c3b-4e83-84c9-025d5650c6e5"),
                            Content = "Post 24 content",
                            Title = "Post 24"
                        },
                        new
                        {
                            Id = new Guid("647898fd-de43-4614-9177-bcde0282b2f5"),
                            CategoryId = new Guid("ffdd0d80-3c3b-4e83-84c9-025d5650c6e5"),
                            Content = "Post 25 content",
                            Title = "Post 25"
                        },
                        new
                        {
                            Id = new Guid("3c979917-437b-406d-a784-0784170b5dd9"),
                            CategoryId = new Guid("ffdd0d80-3c3b-4e83-84c9-025d5650c6e5"),
                            Content = "Post 26 content",
                            Title = "Post 26"
                        },
                        new
                        {
                            Id = new Guid("c27b5903-eeb3-4e82-bf58-f2c123570649"),
                            CategoryId = new Guid("ffdd0d80-3c3b-4e83-84c9-025d5650c6e5"),
                            Content = "Post 27 content",
                            Title = "Post 27"
                        },
                        new
                        {
                            Id = new Guid("dd5c6ed3-197e-48c7-bcce-bce4e3c3de3d"),
                            CategoryId = new Guid("ffdd0d80-3c3b-4e83-84c9-025d5650c6e5"),
                            Content = "Post 28 content",
                            Title = "Post 28"
                        },
                        new
                        {
                            Id = new Guid("f9c8ec2a-b2d3-4e4f-8c29-b0bb3404b860"),
                            CategoryId = new Guid("ffdd0d80-3c3b-4e83-84c9-025d5650c6e5"),
                            Content = "Post 29 content",
                            Title = "Post 29"
                        },
                        new
                        {
                            Id = new Guid("bb4896ee-6c4b-4479-83c8-9534b150b8cb"),
                            CategoryId = new Guid("ffdd0d80-3c3b-4e83-84c9-025d5650c6e5"),
                            Content = "Post 30 content",
                            Title = "Post 30"
                        });
                });

            modelBuilder.Entity("MyBasicWebApiDemo.Models.Post", b =>
                {
                    b.HasOne("MyBasicWebApiDemo.Models.Category", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MyBasicWebApiDemo.Models.Category", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
